import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/component/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "NewsLetter",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Navbar />
				<main className="p-2 bg-slate-50 text-accent-foreground">
					{children}
				</main>
			</body>
		</html>
	);
}
